### ISSUE TITLE
Is this open source?

### ISSUE THREAD

**Issue by davidclayman** [robflaherty/us-map-raphael#5]
Hi Rob,

Two questions:

1) Is this us-map-raphael code on an open source license? 

If you're amenable, I'd like to use this animated map to promote US organ donor registration. Let me know if I've got your blessing to go live with the code as seen at: http://www.optusin.org

2) Can the map be scaled using the .transform("S.75,.75,0,0") Raphael command? Or more permanently, with Inkscape then SVG conversion at web dimensions? I tried both routes, but for the first I can't seem to find the right function call or object to attach the .transform command to. As for the second (scaling in Inkscape, saving to SVG, converting to JS, minifying then alphabetizing), it's exceptionally labor-intensive, and seems error-prone (I'm catching errors in Inkscape's encoding of a reduced-size vector map). 

How would you achieve an arbitrary (say, 85%) scale of usMap?

Sincerely yours,
Clayman, Adam

**Comment by davidclayman** [comment]
Also: I alphabetized the usMap file earlier this morning so that the index counter in mid-execution would match up 1:1 to an external, alphabetized listing of state attributes. Can I contribute back the alphabetized copy? Let me know how I can commit the alphabetized copy to a fork and I'll add it to the repository right away.

**Comment by robflaherty** [comment]
Hi Adam,

1) The map and demo code are both public domain. You can use them however you like. I just updated the readme file to make the licensing clear.

2) To scale the map in Raphael you have to apply the scaling to each individual state, not the canvas. I've done it in the past using the `.scale()` method like this: `usRaphael[state].scale(0.7,0.7, 0, 0);`.

I think that's the way to go. Transforming the source paths can be tricky.

Let me know if that works for you!

**Comment by robflaherty** [comment]
Well... technically object properties are unordered, so the order shouldn't matter :) But I don't see why the paths shouldn't be in alphabetical order. Sure, feel free to submit a pull request. Thanks!
