### ISSUE TITLE
How to change the fill color on the states?

### ISSUE THREAD

**Issue by ArlingtonHouse** [robflaherty/us-map-raphael#6]
First, thanks for this awesome project.  I'm sure the answer is obvious, but how do we set the color that appears upon rollover for each state?  Thanks!

**Comment by robflaherty** [comment]
No problem! The demo uses Raphael's [`getColor()`](http://raphaeljs.com/reference.html#Raphael.getColor) which cycles through colors in the spectrum. If you wanted to specify a color for each state you'd just need to add the color in the loop here (line 35 in the animated demo):

`usRaphael[state].color = Raphael.getColor();`

**Comment by davidclayman** [comment]
Cool, thanks for that!

So check out what I've made at:

http://optusin.org

I've been trying to find an easy way to get the state "Organ Donor Designation" rate to appear either on the map or in a heads-up caption on-hover. I think it'll help a lot to show people which states have outstanding donor designation records (Alaska, Montana), and which ones (namely, Texas, at 10%) have absolutely abysmal organ donor designation rates. I think it'll help a lot if the actual percentages pop up as someone's scanning through the map.

Any thoughts or advice on the steps or libraries involved in getting that done?

Naturally, if you want to help out on visualizing state-by-state organ donor designation rates, please, by all means, feel free to go at that code yourself; I'd more than welcome your help. I'd be happy to release the code on that page as a github opensource project. 

If you want to advise without getting into the code, I'll do the grunt work and get the map updated with your guidance as fast as I can. I think seeing the actual numbers of statewide organ donation commitment disparities printed and colorized on the US map says something meaningful about the organ donation crisis in the US, and might kickstart Texas (~10%) and California (<25%), our two most populous states (25.7 M, 37.7 M) into competitive altruistic social action.

**Comment by robflaherty** [comment]
Adam,

You might try using the tooltip or popover plugins from Bootstrap. Might be tough to integrate with the map though and easier to write something yourself. Raphael's popular enough that there are probably a few plugins/scripts out there specifically for this.

Best,
Rob

**Comment by davidclayman** [comment]
Rob, that's an excellent suggestion, thank you!

**Comment by davidclayman** [comment]
I didn't even know Bootstrap existed, frankly.
