### ISSUE TITLE
Place the demo script on a CDN

### ISSUE THREAD

**Issue by silasjmatson** [robflaherty/us-map-raphael#9]
For the demo linked to in the readme, you are using Github as a CDN, which doesn't work, because it's served with a mime type of 'text/plain' and isn't executable.

**Comment by robflaherty** [comment]
Thanks! Found some info about it here: https://plus.google.com/+MikeWest/posts/28f8HS2M7cb

Going to move the scripts over to a Pages branch and update the demo links.
